version: '3.8'
services:
  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
    command: ["tidb-server", "--store=unistore"]

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - tidb
      - kafka
    environment:
      - DB_HOST=tidb
      - DB_PORT=4000
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=sre_assignment
      - KAFKA_BROKER=kafka:9092

  consumer:
    build: .
    command: node consumer.js
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092